### ISSUE TITLE
get create_etd_spec running in qa environment

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/infrastructure-integration-test#128]
We want the qa environment set up such that:

- [x] infrastructure-integration-tests
  - [x] [enable switching between QA and staging envs](https://github.com/sul-dlss/infrastructure-integration-test/pull/129)
- [x] ETD app
  - [x] [shared_configs](https://github.com/sul-dlss/shared_configs/tree/sul-hydra-etd-qa)
  - [x] [puppet](https://github.com/sul-dlss/operations-tasks/issues/2307)
  - [x] [capistrano](https://github.com/sul-dlss/hydra_etd/pull/661)
  - [x] [integration test works through ETD app steps](https://github.com/sul-dlss/infrastructure-integration-test/issues/128)
- [x] Argo
  - [x] [shared_configs](https://github.com/sul-dlss/shared_configs/tree/argo-qa)
    - [x] [regenerate DSA token to fix 401 errors](https://github.com/sul-dlss/shared_configs/commit/e2b1a48bcb9f0e04872022369805aa13acf3a74c)
  - [x] [puppet node-a](https://github.com/sul-dlss/puppet/blob/production/hieradata/node/argo-qa-a.stanford.edu.eyaml) and [puppet node-b](https://github.com/sul-dlss/puppet/blob/production/hieradata/node/argo-qa-b.stanford.edu.eyaml)
  - [x] [capistrano](https://github.com/sul-dlss/argo/blob/master/config/deploy/qa.rb)
  - [x] create [ETD APO in qa](https://argo-qa.stanford.edu/view/druid:bx911tp9024) based on [ETD APO in stage](https://argo-stage.stanford.edu/view/druid:bx911tp9024)
  - [x] [fix shibboleth in QA](https://github.com/sul-dlss/operations-tasks/issues/2314) - will know this is fixed once you can click e.g. [`etdSubmitWF`](https://argo-qa.stanford.edu/view/druid:wv456ww0683)
  - [x] [integration test works through end](https://github.com/sul-dlss/infrastructure-integration-test/issues/128)

**Comment by mjgiarlo** [comment]
@ndushay :speech_balloon: 
> Additionally:
> 
> * [ ]  want dev to be able to run an etd from creation through accessioning, per [sul-dlss/hydra_etd#596 (comment)](https://github.com/sul-dlss/hydra_etd/issues/596#issue-662148601)
> 
> related to [sul-dlss/hydra_etd#547](https://github.com/sul-dlss/hydra_etd/issues/547)

I would like to remove this from the scope of #128 and focus just on getting the current spec to pass. OK by you?

**Comment by ndushay** [comment]
> I would like to remove this from the scope of #128 and focus just on getting the current spec to pass. OK by you?

sure.  I suppose having accessioning actually work in qa is ... another matter.

**Comment by mjgiarlo** [comment]
The ETD spec now passes in QA. Closing.
